### ISSUE TITLE
3 very important addresses

### ISSUE THREAD

**Issue by StrongTequila** [ignaciocastro/a-dove-is-dumb#1]
For some reason you don’t have them, without them Illustrator on a Mac immediately stops working. Maybe you don't work with apple
127.0.0.1 iu7mq0jcce.adobestats.io
127.0.0.1 tdatxzi3t4.adobestats.io
127.0.0.1 rptowanjjh.adobestats.io
I can see these addresses through the Little Snitch firewall, I can regularly add addresses of Apple versions

**Comment by ignaciocastro** [comment]
**✅ Done**. Thank you!

**Comment by ozgurkazancci** [comment]
> I can see these addresses through the Little Snitch firewall, I can regularly add addresses of Apple versions

Hi. I've been using Little Snitch in past years, so Little Snitch still prevents Adobe from being catched? If so, what's the purpose of manually updating the hosts, if we can completely block the software with firewall?

Best.

**Comment by StrongTequila** [comment]
> Hi. I've been using Little Snitch in past years, so Little Snitch still prevents those softwares from being catched? If so, what's the purpose of manually updating the hosts, if we can completely block the software with firewall?
> 
You can, it works great, create rules for each application

**Comment by ozgurkazancci** [comment]
Yes, that's where I don't really get the logic on adding new hosts each time, if we can completely block the software through a fw.

Little Snitch was working very fine for years. The point I don't get, why don't we simply block all the incoming/outgoing connection of those programs, instead of manually blocking new host each time? Any idea @ignaciocastro on this please?

Regarding the software firewall; this is very good one for Windows:

https://www.sordum.org/8125/firewall-app-blocker-fab-v1-9/

**Comment by ignaciocastro** [comment]
Hi @ozgurkazancci, @StrongTequila. Some people still use cloud functionalities and don't want to lose connectivity to that part, hence the reason this list exists. If you can turn off your wi-fi or block the program with your firewall then it might be a better option, but out of the scope of this repository. Continuing with my explanation might put this repository at risk once again so I will be locking it down. Thanks for your continued support!
