### ISSUE TITLE
Unlicensed popups are back

### ISSUE THREAD

**Issue by GoldfishGinta** [ignaciocastro/a-dove-is-dumb#13]
I think I'm supposed to submit an issue when this happens? Have manually updated using https://a.dove.isdumb.one/list.txt no luck.

**Comment by futiele** [comment]
yep. i met 2. what should we do to help troubleshoot this problem?

**Comment by ignaciocastro** [comment]
"Adobe tends to update their telemetry checking subdomain every two weeks. Feel free to open [an issue](https://github.com/ignaciocastro/a-dove-is-dumb/issues/new) if you already tried updating the list and nothing happened. **It'd be appreciated if you could use Fiddler / Charles Proxy when opening the program, sort by "/integritychecker/machineevents/v1" and include the subdomain it was requested from. Please include the URL as text instead of just pasting a screenshot, your submission will be rejected if you don't paste the URL.**"

Also, please stop using that first word

**Comment by GoldfishGinta** [comment]
I don't understand "sort by "/integritychecker/machineevents/v1" and include the subdomain it was requested from" but using Charles and some trial & error, I've found that the IP causing the problem is a2104gz1mh.adobe.io

**Comment by ignaciocastro** [comment]
> I don't understand "sort by "/integritychecker/machineevents/v1" and include the subdomain it was requested from" but using Charles and some trial & error, I've found that the IP causing the problem is a2104gz1mh.adobe.io

This was added some days ago thanks to your contribution. Have a nice day!
