### ISSUE TITLE
[Question] Why not just wildcard the domains?

### ISSUE THREAD

**Issue by Permanently** [ignaciocastro/a-dove-is-dumb#23]
Why not just wildcard-block *.adobe.io, *.prod.cloud.adobe.io and *.adobestats.io? Is there functionality being served over subdomains as well, or is there a lack of wildcard functionality on the blocking side of that we need to be aware of?

**Comment by ozgurkazancci** [comment]
I wonder that, too.

**Comment by Permanently** [comment]
I feel that answer falls short of what's trying to be figured out here, especially with the postscript. If I can wildcard on PiHole, then what's the rationale behind that if you don't recommend it anyway, even after you've said that if I can then "this repository is too simple for you"? Additionally, why is it that adobestats.io could be wildcarded (an assumption), but not adobe.io?

What I'm trying to get at here is, are some of these domains purely telemetry? Or, are some of them providing core services that we need to be wary of?

**Comment by ignaciocastro** [comment]
It was a simplistic reply for a simple repository. As of now, only *.adobe.io domains are not recommended to be wildcarded because there's more services running on them. The thing is, we don't know whether Adobe feels like migrating them to *.adobestats.io ever, so I don't encourage wildcarding in this repository. Again, **this is a historical list of subdomains**. If you have the ability of using wildcards, **do not use this repository and do the wildcard by yourself**

Issue locked
